const Langues = {
    FRENCH: {
      langue: {
        siteInfo: "Développer une stratégie de Marketing",
        siteTexte1: "Nous vous proposons du contenu marketing pour votre entreprise,",
        MenuSite:"Création de site",
        MenuBussness:"Marketing",
        MenuAnnonce:"Devenez annonceur",
        QuiSommeNous:"Qui somme nous",

        Presentation:"Nous vous proposons du contenu marketing pour votre entreprise",
        PresentationTexte1:"Donnez vie à votre vision avec nos services de création de contenu de qualité supérieure.",
        PresentationTexte2:"Attirez l'attention de votre public cible avec notre contenu créatif et engageant.",
        PresentationTexte3:"Maximisez votre présence en ligne grâce à notre stratégie de création de contenu personnalisée.",
        CreateMarketingContent:"Crée du contenu marketing",
        Createawebsite:"Crée un site internet",

        TheListesecureManuel: 'Liste manuel de sécurité',
        ThesecureManuel: 'Manuel de sécurité',
        Addthenewsletter: 'Ajouter une newsletters',
        ThePrincipalmailadresse: 'Adresse Email parent principal',
        ThePrincipalphonecontact: 'Téléphone parent principal',
        Thecantinefess: 'Frais de cantine',
        AddingThecantinefess: 'Ajouter des frais de cantine',
        NoReportCardAvailaible: 'Aucun bulletin disponible',
        NoMessagestandbyTovalidate: 'Aucun message en attente de validation',
        MessagestandbyTovalidate: 'Messages en attente de validation',
        ThestatutValider: 'Valider',
        ThestatutStandby: 'En attente de validation',
        ThestatutAlls: 'Tous',
        TheActions: 'Actions',
        TheMessageLibelle: 'Libellé du message',
        Theclasses: 'Classes',
        ThedevoirLibelle: 'Libellé du devoir',
        TheAddby: 'Ajouter par',
        TheFile: 'Fichier',
        Thelien: 'Lien',
        NoDevoirstandbyTovalidate: 'Aucun devoir en attente de validation',
        DevoirstandbyTovalidate: 'Devoirs en attente de validation',
        TheBtnClose: 'Fermer',
        PlanIsAccepted: 'Plan accepté',
        OurFamilies: 'Notre famille',
        Soldee: 'Soldé',
        Solde: 'Solde',
        NoSoldee: 'Non Soldé',
        TheplanA: 'Plan A',
        TheplanB: 'Plan B',
        TheplanC: 'Plan C',
        TheplanD: 'Plan D',
        Admins: "Administration",
        Atcharge: 'A la charge de',
        MontantEcheance: 'Montant échéance',
        EcheanceDate: 'Date échéance',
        TheBtnDelete: 'Supprimer',
        AgreeFolder: 'Accepter le dossier',
        AgreeCandidature: 'Accepter la candidature',
        Thedatails: 'Détails',
        SeePlan: 'Voir le plan',
        ChoiceTheclasse: 'Choix de la classe',
        Thestandby: 'En attente',
        Thecurrently: 'En cours',
        TheValidateFolder: 'Dossier valider',
        TheSbmitFolder: 'Dossier soumis',
        TheStandbyFolder: 'Dossier en attente',
        ThepaiementPlanSubmit: 'Plan de paiement soumis',
        TheStatutInscrit: 'Inscrit',
        Theperiodes: 'Périodes',
        SelectTheperiodes: 'Sélectionner une période',
        TheFiles: 'Fichiers',
        TheFilesStudents: "Fichiers de l'élève",
        SubmitedBy: 'Soumis par',
        NoCahierstandbyTovalidate: 'Aucun cahier journal en attente de validation',
        CahierstandbyTovalidate: 'Cahiers journaux en attente de validation',
        NoBulletinstandbyTovalidate: 'Aucun bulletin en attente de validation',
        BulletinstandbyTovalidate: 'Bulletins en attente de validation',
        TheMatricules: 'Matricules',
        TheMatricule: 'Matricule',
        TransportManagement: 'Gestion du transport',
        ThecircuitLists: 'Liste des circuits',
        TheStandards: 'Standards',
        Themontantdu: 'Montant dû',
        Themontantverser: 'Montant versé',
        TasksManagement: 'Gestion des taches',
        Reinscriptionform: 'Formulaire de réinscription',
        Inscriptionform: "Formulaire de d'inscription",
        Candidatureform: "Formulaire de candidature",
        PreviousClasse: 'Classe précédente',
        Displayrecap: 'Afficher le récap',
        Presences: 'Présences',
        Retards: 'Retards',
        ProfileUser: 'Profile utilisateur',
        Nodocumentactually: 'Aucun document disponible',
        At:"Au",
        Transportobservations:"Merci de renseigner les montants de plus 1e fois séparé par un tiret (-)",
        AnnualFees3times:"Frais annuel en 3 fois",
        AnnualFees2times:"Frais annuel en 2 fois",
        AnnualFees1times:"Frais annuel en 1 fois",
        TrimestrialFees:"Frais trimestriel",
        MensualFees:"Frais mensuel",
        TheMensual:"Mensuel",
        ListTransportFees:"Liste des frais de transport",
        AddTransportFees:"Ajout des frais de transport",
        TheFees:"Frais",
        TheMontant:"Montant",
        TheTransportType:"Type de transport",
        TheSimpleTrajet:"Trajet simple",
        TheMixteTrajet:"Trajet mixte",
        TheSimpleTrajetAllerRetour:"Trajet simple aller et retour",
        TheSimpleTrajetAllerOuRetour:"Trajet simple aller ou retour",
        TheCircuits:"Circuits",
        TheRecapofDocument:"Récapitulatif des documents",
        TheSMSstatitics:"Statistiques SMS",
        TheUsed:"Utiliser",
        TheUnUsed:"Restes",
        TheTeacherAssistant:"Assistant teacher",
        TheTeacherAssistantList:"Liste des enseignants assistant",
        TheRoles:"Roles",
        TheAVS:"AVS",
        TheAVSlist:"Liste des AVS",
        TheParents:"Parents",
        TheUsers:"Utilisateurs",
        TheTimestablelists:"Liste des emplois du temps",
        Recherchereffec:"Effectuer une recherche",
        UpdateTimestablefile:"Modifier le support de l'emploi du temps",
        ListOfStudents:"Liste des élèves",
        AllsStudents:"Tous les élèves",
        Girlsudents:"Filles",
        Malesudents:"Garçons",
        Girlsudent:"Fille",
        Malesudent:"Garçon",
        TheInscrits:"Inscrits",
        TheReInscrits:"Réinscrits",
        TheTransfert:"Transfert",
        TheStandardList:"Liste des standards",
        ThesousStandardList:"Liste des sous standards",
        TheNewStandard:"Nouveau standard",
        TheNewsousStandard:"Nouveau  sous standard",
        TheLangue:"Langue",
        TheClassetypes:"Types de classe",
        ScolariesYearList:"Liste des années scolaires",
        ScolariesYear:"Années scolaires",
        AddScolariesYear:"Ajouter un année scolaire",
        TheEffectifs:"Effectifs",
        TheActivestate:"Actif",
        TheInActivestate:"Inactif",
        ListOfReportCards:"Liste des bulletins",
        BtnPublier:"Publier",
        TheObjet:"Objet",
        NoListeAvailable:"Aucune liste disponible",
        TheLibelleFr:"Libelle en Fr",
        TheLibelleEN:"Libelle en An",
        AddThenewLibelle:"Ajouter un nouveau libellé",
        UpdateTheLibelle:"Mofifier le libellé",
        TheListofLibelle:"Liste des libellés",
        TheDaterainsList:"Liste des dates à retenir",
        CandidaturesManagement:"Gestion des candidatures",
        ThePrinted:"Imprimer",
        ListofPrograms:"Liste des programmes",
        Thenewprogram:"Nouveau programme",
        TheVersementList:"Liste des versements",
        AddTheVersement:"Ajouter un versement",
        TheVersementDate:"Date versement",
        TheBeneficiaires:"Bénéficiaires",
        TheTrajets:"Trajets",
        ThePrenameUsual:"Prénom usuel",
        TheNewassignation:"Nouvelle assignantion",
        AssignationAtEtabs:"Assignation à un établissement",
        TheProfile:"Profile",
        TheclasseNumbers:"Nombre de classes",
        AssignateAclasseForTeacger:"Assigner une classe au professeur",
        ClasseAmount:"Montant de la classe",
        Thetypes:"Types",
        ParentsList:"Liste des parents",
        ParentPrincipal:"Parent principal",
        ParentSecondaire:"Parent secondaire",
        FamilleLogin:"Login famille",
        ThecompteType:"Type de compte",
        Listedelaclasse:"Liste de la classe",
        ExcelExport:"Exporter en excel",
        ExcelExportplus:"Exporter en excel avec plus de détails",
        TotalEffectif:"Effectif total",
        BtnConsulter:"Consulter",
        BtnNoConsulter:"Non Consulter",
        ListeMenuCantine:"Liste des menus",
        StudentNumbers:"Nombre d'élèves",
        ThedemandeList:"Liste des demandes",
        ListeDescahierjournaux:"Liste des cahiers journaux",
        MontantAnnual:"Montant annuel",
        MontantTrimestriel:"Montant trimestriel",
        ListeAccuserReceptions:"Liste accusé de reception",
        Currentlyschools:"Ecole actuelle",
        WhatisthefamilleStatus:"Quel est le statut de la famille de cet élève ?",
        SelectStatusofthisfaimily:"Sélectionner le statut de la famille",
        Thenewsfaimily:"Nouvelle famille",
        Theoldersfaimily:"Ancienne famille",
        SearchTheloginfamille:"rechercher le login famille",
        Theprofession:"Profession",
        TheEmployeur:"Employeur",
        PostaleAdresse:"Adresse postale",
        TheEmetteurs:"Emetteurs",
        TheSoumis:"Soumis",
        DateValidation:"Date validation",
        TheEtat:"Etat",
        TheLastconnexion:"Dernière connexion",
        TheconnectionNumbers:"Nb de fois connecter",
        NeitherConnected:"Jamais connecter",
        TodayConnected:"Connecter aujoud'hui",
        TheclasseGallery:"Galerie de la classe",
        ManagementGallery:"Gestion de la Galerie",
        TheclasseListe:"Liste de classe",
        CorrectifyBirthdays:"Correction des dates de naissance",
        FolderValidation:"Validation des documents",
        ElevesSortants:"Elèves sortants",
        Programsdetails:"Détails du programme",
        Thegeneralinfos:"Informations générales",
        MessageDetails:"Détails du message",
        Messagerieboites:"Boite de messagerie",
        NewMessage:"Nouveau message",
        Boitereceptions:"Boite de réception",
        Answered:"Répondre",
        HmeworkDetails:"Détails de l'exercice a faire",
        Classedetails:"Détails de la classe",
        Candidaturestep1:" 1 Une photo d'identité",
        Candidaturestep2:" 2 Un extrait de naissance",
        Candidaturestep3:" 3 Un certificat de vaccination ou Une copie de vaccination du carnet",
        Candidaturestep4:" 4 Le livret scolaire ou Le(s) bulletin(s) des années précédentes",
        Candidaturestep5:" 5 Le certificat de fréquentation ou de radiation",
        FileImagetocandidate:"Type de fichier à ajouter : Jpg,Jpeg,png",
        Filepdftocandidate:"Type de fichier à ajouter : pdf",
        ChampObligatoires:"Champs obligatoires",
        PersonnalInformations:"Informations personnelles",

        FileAttached:"Fichier joint",
        Nationalite2: 'Nationalité 3',
        Listedateanniversaires:"Liste des dates anniversaires",
        TheEtabs:"Etablissements",
        TheMessageSends:"Messages envoyés",
        TheUnreadMessages:"Messages non lus",
        TheAllMessages:"Tous les messages",
        To:"De",
        ValiderAbulletin:"Valider un bulletin",
        ReceptionAccused:"Accusé de réception",
        AddAbulletin:"Ajouter un bulletin",
        RdvParents:"Rendez-vous parents",
        ManagementCalendars:"Gestion des calendriers scolaires",
        IbsaCalendars:"Calendriers IBSA",
        ParentaleAccord:"Autorisation parentale",
        ClasseChangement:"Changement de classe",
        EtabsChangement:"Changement d'établissement",
        ClasseCurrent:"Classe actuelle",
        SelectDestinataires:"Sélectionner les destinataires",
        PaiementPlan:"Plan de paiement",
        ManageThedateRetains:"Gestion des dates à retenir",
        WhatChildsTalents:"Quels sont, selon vous, les points forts et les talents particuliers de votre enfant?",
        WhyIbsa:"Pourquoi avez-vous choisi IBSA ?",
        WhatpsychoChild:"Votre enfant a-t-elle/il déjà reçu une évaluation psycho/neuro-pédagogique ? si oui, veuillez fournir des copies du rapport.",
        Isexpulseallready:"Votre enfant a-t-il déjà été suspendu ou expulsé de l'école ?",
        DoyoServiceconnexe:"Avez-vous besoin des services scolaires suivants ?",
        InternatLogement:"Logement internat",
        Nobesoinsconnexe:"Je n'est pas besoin de ces services",
        Theother:"Autre",
        RespoPrincipal:"Parents Principal interlocuteur de l'équipe scolaire",
        WhoIsPrincipal:"Qui est le principal interlocuteur ?",
        WhoIsPrincipal:"Qui est le principal interlocuteur ?",
        TheFather:"Père",
        TheMother:"Mère",
        TheTutor:"Tuteur",
        TheWhatsAppPhone:"Contact WhatsApp",
        TheLocalisation:"Adresse géographique",
        TheCountry:"Pays",
        TheTown:"Ville",
        TheQuatier:"Quartier",
        TheSecondParent:"Deuxième parent",
        TheNAchoice:"N/A (Cocher cette case s'il n'y a pas de deuxième parent à saisir.)",
        WhoIsTheSecondParent:"Qui est le deuxième parent?",
        UrgencePerson:"Personne à contacter en cas  d'urgence",
        HomePhone:"Domicile",
        MedicalInfo:"Information medical",
        MedicalForm:"Fiche de renseignements médicaux",
        GroupeSanguin:"Groupe sanguin",
        TheClinique:"Clinique/Hopital",
        TheCliniqueMat:"Numéro matricule Enfant / clinique",
        TheCMU:"Numéro CMU",
        TheAssurance:"Numéro d'assurance",
        TheMedicalAnte:"Antécédents médicaux",
        TheEnfant:"Enfant",
        TheAsthme:"Asthme",
        TheDrepa:"Drépanocytose",
        TheCardiopat:"Cardiopathie",
        TheEpilesp:"Epilepsie",
        TheHupert:"Hypertension",
        TheRhumat:"Rhumatisme",
        TheSpiri:"Aspirine",
        TheMedcinTraitant:"Médecin traitant",
        PhoneTheMedcinTraitant:"Telephone Médecin traitant",
        TheAllergies:"Allergies",
        TheSerum:"Sérum antitétanique",
        TheNivaquine:"Nivaquine",
        ThePeniciline:"Pénicilline",
        TheLode:"Lode",
        TheAllergieAliment:"Allergies alimentaire(s)",
        TheOtherAllerg:"Autre allergie",
        TheInfantdeases:"Maladies infantiles",
        TheRougeol:"Rougeole",
        TheOreillonsl:"Oreillons",
        TheVaricel:"Varicelle",
        TheScartine:"Scarlatine",
        TheNext:"Suivant",

        NbAbsences:"Nombre d'absences",
        NbRetards:"Nombre de retards",
        Thestatitistics:"Statistiques",
        TheWelcome:"Bienvenue",
        TheVersementState:"Etat des versements",
        TheLoginBtn:"Connexion",
        Thescolarities:"Scolarités",
        Weeklydabalys:"Menu de la semaine",
        TheAtLe:"à",
        TheRef:"REF",
        PeriodeDu:"Période du",
        NoprogramAvailable:"Aucun programme disponible",
        Seeprogramme:"Voir le programme",
        Whouldreinscrire:"Je désire réinscrire mon enfant",
        Completefolder:"Completer le dossier",
        InfoAboutBulletin:"Informations sur le bulletin",
        Programsupport:"Support du programme",
        ProgramInfo:"Informations  sur le programme",
        TimestableInfo:"Informations  sur l'emploi du temps",
        Messagefiltre:"Filtre messages",
        TheStudentInfos:"Informations Elèves",
        TheclasseThat:"La classe de",
        Myclasses:"Mes classes",
        Myclassinfo:"Info Classe",
        NoHomeworkavailbale:"Aucun exercie disponible",
        TheCahierjournaux:"Cahiers journaux",
        UpdateProgramFiles:"Modifier le support du programme",
        UpdateBulletinFiles:"Modifier le support du bulletins",
        AddaTimestablenew:"Ajouter un nouveau emploi du temps",
        Addanewnotebook:"Nouveau cahier journal",

        Thenewslettres:"Newsletters",
        Updatenewslettres:"Modifier la newsletters",
        deletenewslettres:"Supprimer la newsletters",
        validatenewslettres:"Valider la newsletters",
        Nonewslettres:"Aucune newsletters",
        dateparutionewslettres:"Date de parution",
        lienparutionewslettres:"Lien newsletters",
        typeewslettres:"Type newsletters",
        lastnewslettres:"Dernière newsletters",
        NoTimestables:"Aucun emplois du temps disponible",
        SelectNewsletterTypes:"Sélectionner un type",

        SearchingByprenom:"Rechercher un élève par son prénom",
        FinancialDetails:"Information financière",
        TotalVersementInscrip:"Total Versements  Inscriptions",
        TotalVersementReInscrip:"Total Versements  Réinscriptions",
        TotalVersementScolarites:"Total Versements  Scolarités",
        TotalVersementTransports:"Total Versements  Transports",
        TotalVersementAes:"Total Versements  AES",
        Thescolaritiescaps:"SCOLARITES",
        Theinscriptioncaps:"INSCRIPTIONS",
        Thereinscriptioncaps:"REINSCRIPTIONS",
        Thetransportcaps:"TRANSPORTS",
        Theaescaps:"AES",
        Theversements:"Versements",










        Bibliothequemanagement: 'Gestion de la bibliothèque',
        BibliotheqeuCahiers: 'Bibliothèque des cahiers journaux',
        BibliotheqeuNewsletters: 'Bibliothèque des newsletters',
        InscriptList: 'Liste des inscrits',
        ReInscriptList: 'Liste des réinscrits',
        ActivitiesListe: 'Liste des activités',
        NewActivity: 'Nouvelle activité',
        ManagementAES: 'Gestion des activités extra-scolaire',
        FonctionAdmin: 'Administrateur',
        FonctionPolyvalent: 'Agent polyvalent',
        FonctionCE: "Chef d'établissement",
        FonctionChefcompta: "Chef comptable",
        FonctionBdm: "Business Development Manager",
        FonctionComptable: "Comptable",
        FonctionCoordinateur: "Coordinateur / Coordinatrice",
        FonctionCoordinateurCAes: "Coordinatrice des Admissions et AES ",
        FonctionCoordinateurCc: "Curriculum Coordinator",
        FonctionCoordinateurCd: "Curriculum Director",
        FonctionCoordinateurDaf: "Directeur / Directrice Administratif et Financier",
        FonctionCoordinateurDg: "Directrice générale",
        FonctionCoordinateurIntendance: "Intendance",
        FonctionCoordinateurMarketing: "Marketing",
        FonctionCoordinateurSuperviseur: "Superviseur",
        FonctionCoordinateurCharged: "Chargé des admissions",
        FonctionCoordinateurPcg: "Président du Conseil de Gestion",
        SelectTheFonction: 'Sélectionner une fonction',
        TheFonction: 'Fonction',
        TheFonctions: 'Fonctions',
        GenderF: 'F',
        GenderM: 'M',
        ThenewUser: 'Nouveau utilisateur',
        UsersLists: 'Liste des Utilisateurs',
        ManagementParameters: 'Gestion des paramètres',
        UploadPhoto: 'Charger la photo',
        Photo: 'Photo',
        ClassPhoto: 'Photo de classe',
        StudentPhoto:"Photo d'élève",
        Login: 'Login',
        SelectGenre: "Sélectionner un genre",
        ListofTeachers: "Liste des enseignants",
        NewTeacher: "Nouvel enseignant",
        SendMessage: "Envoyer le message",
        TheMessage: "Message",
        ObjetMessage: "Objet du message",
        TitreMessage: "Titre du message",
        ManagementMessage: "Gestion de la messagerie",
        TheSMS: "SMS",
        SeeMore: "Voir plus",
        PrintedInvoice: "Imprimer le reçu",
        Nopaiement: "Aucun paiement",
        Newpaiement: "Nouveau paiement",
        Validatepaiement: "Valider le paiement",
        Thedatepaiement: "Date de paiement",
        Resteapeyer: "Reste à payer",
        Montantversement: "Montant versement",
        Montantapayer: "Montant à payer",
        TheDu: "Du",
        ModePaiementCheque: "Chèques",
        ModePaiementEspece: "Espèces",
        ModePaiementTpe: "TPE",
        ModePaiementVirement: "Virement bancaire",
        SelectModePaiement: "Sélectionner un mode de paiement",
        ModePaiement: "Mode de paiement",
        TrajetAllerRetour: "trajet aller et retour",
        TrajetAllerouRetour: "trajet aller ou retour",
        SelectTheTrajet: "Sélectionner un trajet",
        TheTrajet: "Trajet",
        TheAnnuel: "Annuel",
        Thetrimestriel: "Trimestriel",
        SelectTheforfait: "Sélectionner un forfait",
        Theforfait: "Forfait",
        SelectTheActivite: "Sélectionner une activité",
        TheActivite: "Activité",
        TheAES: "AES",
        SelectTheMotif: "Sélectionner un motif",
        TheMotif: "Motif",
        TheMotifs: "Motifs",
        Thedeposantphone: "Téléphone Déposant",
        Thedeposant: "Déposant",
        ManagementThepaiement: "Gestion des paiements",
        Thepaiement: "Paiement",
        CantineManagement: "Gestion de la cantine",
        AddMenucantine: "Ajouter un menu",
        TheLibelle: "Libellé",
        TheDatedeb: "Date de début",
        TheDatefin: "Date de fin",
        TheTitre: "Titre",
        Addpicture: "Ajouter une photo",
        TheHomeworksupport: "Support de l'exercice à faire",
        TheNon: "NON",
        TheOui: "OUI",
        Lockafterexpiration: "Verrouiller l'exercice du côté de l’élève après l’échéance",
        SelectStudent: "Sélectionner un élève",
        BtnAnnuler: "Annuler",
        IndividualHomework: "Exercice individuel",
        ClasseHomework: "Exercice de classe",
        TheLimitdate: "Date limite",
        LibelleHomeworks: "Libellé exercice",
        NoTheMatiere: "Aucune matière",
        SelectTheMatiere: "Sélectionner une matière",
        TheMatiere: "Matière",
        HomeworkInfo: "Informations sur l'exercice à faire.",
        AddHomework: "Ajouter un Nouvel exercice à faire",
        HomeworkLists: "Liste des exercices à faire",
        TheDescription: "Description",
        AnDescription: "Description AN",
        FrDescription: "Description FR",
        TheHour: "Heure",
        TheAlls: "Tous",
        Destinataires: "Destinataire (s)",
        SelectLibelleActiviteFr: "Sélectionner le libellé en FR",
        SelectLibelleActiviteEn: "Sélectionner le libellé en AN",
        LibelleActiviteFr: "Libellé Activité (Fr)",
        LibelleActiviteEn: "Libellé Activité (En)",
        InfoAboutNationalHolidays: "Information sur la fête nationnal",
        InfoAboutDatereatins: "Information sur la date à retenir",
        NationalHolidays: "Fêtes nationales",
        Addnewdate: "Ajouter une nouvelle date",
        ListDateAndfetes: "Liste des dates et Calendrier des Fêtes nationales",
        CalendarNationalHolydays: "Calendrier des Fêtes nationales ",
        BtnSave: "Enregistrer",
        SelectNiveauClasse: "Séléctionner le niveau de la classe",
        NiveauClasse: "Niveau classe",
        ReInscriptionsFees: "Frais de réinscription",
        InscriptionsFees: "Frais d'inscription",
        ScolaritesFees: "Frais de scolarité",
        Libelleclassefr: "libellé classe (Francais)",
        LibelleclasseEn: "libellé classe (Anglais)",
        Newclasse: "Nouvelle classe",
        Listofclasses: "Liste des classes",
        ImportFile: "Importer le fichier",
        SelectThestudent: "Sélectionner un élève",
        Thestudent: "Elève",
        SelectThetrimestre: "Sélectionner un trimestre",
        Thetrimestre: "Trimestre",
        InfoTips: "Informations",
        OnReportcard: "sur le bulletin",
        AddnewreportCard: "Ajouter un nouveau bulletin",
        BtnValider: "Valider",
        StatutAbsent: "Absent",
        StatutPresent: "Présent",
        StatutRetard: "Rétard",
        Thecommentaire: "Commentaire",
        SelectThestatut: "Selectionner un statut",
        Thestatut: "Statut",
        Thestatuts: "Statuts",
        NameAndPrename: "Noms & prénoms",
        SelectTheclasse: "Sélectionner une classe",
        Theclasse: "Classe",
        Admin: "Administration",
        SelectTeacher: "Sélectionner un enseignant",
        Teacher: "Enseignant",
        Teachers: "Enseignants",
        SelectThePersonneltype: "Sélectionner le type de personnel",
        ThePersonnel: "Personnel",
        Thedate: "Date",
        StudentAttendences: "Assiduité des élèves",
        StaffAttendences: "Assiduité du personnel",
        RecapStudentAttendences: "Récap Assiduité des élèves",
        RecapStaffAttendences: "Récap Assiduité du personnel",
        ManagementAbsences: "Gestion de l'assiduité",
        TheAbsences: "Assiduité",
        Reregistrationdemande: 'Demande de réinscription',
        hello: 'Bienvenue sur la Liaison numérique Famille - École',
        Home: 'Accueil',
        Calendriers: 'Calendriers',
        Candidatures: 'Candidatures',
        Enquetes: 'Enquetes',
        GestionsEleves: 'Gestion des élèves',
        Eleves: 'Elèves',
        TheEleves: 'Elèves',
        Transports: 'Transports',
        Enseignement: 'Enseignement',
        Enseignements: 'Enseignements',
        Assiduites: 'Assuiduités',
        Bulletins: 'Bulletins',
        Bibliotheque: 'Bibliotheque',
        AExtra: 'Activités Extra-scolaire',
        Messages: 'Messages',
        Administration: 'Administration',
        Galerie: 'Galerie',
        Tasks: 'Taches',
        Dateretains: 'Date à retenir',
        Francais: 'Français',
        Anglais: 'English',
        Inscription: 'Inscription',
        Inscriptions: 'Inscriptions',
        Reinscription: 'Réinscription',
        Reinscriptions: 'Réinscriptions',
        Familles: 'Familles',
        FamillesListes: 'Liste des familles',
        Classes: 'Classes',
        Monitoring: 'Monitoring',
        HitoriqueCnx: 'Historique de connexion',
        HistoriqNotifs: 'Historique des notifications',
        HistoriqCahiers: 'Historique des cahiers journaux',
        Deconnexion: 'Déconnexion',
        Account: 'Mon compte',
        CahierJournal: 'Cahier journal',
        Cahierliaison: 'Cahier de liaison',
        Devoirs: 'Devoirs',
        Cantines: 'Cantines',
        Anneescolaires: 'Année scolaire',
        Emploisdutemps: 'Emploi du temps',
        Programmes: 'Programmes',
        Programme: 'Programme',
        Calendrierscolaire: 'Calendrier scolaire',
        ManuelParent: 'Manuel parent',
        Accountdetails: 'Détails du compte',
        Changepictureprofile: 'Changer la photo de profile',
        Choosepicture: 'Choisir une image',
        Informations: 'Informations',
        Accountinfos: 'Informations du compte',
        Parameters: 'Paramètres',
        FavoriteLangue: 'Langue préférée',
        AccountName: 'Nom du compte',
        Name: 'Nom',
        PreName: 'Prénoms',
        Genre: 'Genre',
        Masculin: 'Masculin',
        Feminin: 'Féminin',
        Datenais: 'Date de naissance',
        Lieunais: 'Lieu de naissance',
        Nationalite: 'Nationalite',
        Nationalite1: 'Nationalite 2',
        Fonction: 'Fonction',
        AdresseEmail: 'Adresse email',
        Telephone: 'Téléphone',
        MobileTelephone: 'Téléphone mobile',
        WorkTelephone: 'Téléphone bureau',
        Leschamps: 'Les champs ',
        Obligatoires: 'sont obligatoires ',
        ModifierBtn: 'Modifier',
        ParametresCnx: 'Paramètre de connexion',
        Password: 'Mot de passe',
        Password1: 'Confirmation',
        PleaseAddpasswords: 'Merci de renseigner les mot de passe',
        PleaseAddthesamepasswords: 'Merci de renseigner les mot de passe identiques',
        PleaseAddChampsObligatoires: 'Merci de renseigner les champs obligatoires',
        Calendrierscolaire: 'Calendrier scolaire',
        ManuelParent: 'Manuel parent',
        Parentskit:'La malette Parent',
        ParentHandbook:'LE MANUEL DES PARENTS',
        SchoolCalendar:'CALENDRIER SCOLAIRE',
        Curriculum:'PROGRAMME DE LA CLASSE',
        Weeklyagenda:'Agenda de la semaine',
        Digitalteachingtools:'Les outils pédagogiques numériques',
        FriendsofIBSA:'Amis de IBSA',
        Myschoolapps:'Mes applications pédagogiques',
        PaymentsHistory:'Historique des paiements',
        PaymentsHistoryAES:'Historique des paiements AES',
        Datestoremember:'Dates à retenir',
        IBSAHighSchoolDiploma:'Le diplome IBSA',
        Parentconferences:'Réunions parent-enseignant',
        Weeklyprograms:'Cahier journal',
        Correspondencebook:'Cahier de Liaison',
        Studentsheet:'La Fiche Elève',
        Reportcards:'Bulletins',
        Absences:'Absences',
        tardiveness:'Retards',
        Document:'Document',
        Gallery:'Galerie',
        Weekof:'SEMAINE DU',
        Assignement:'Devoir de maison',
        Downloader:'Télécharger',
        //Menu
        Souscriptions:'Souscriptions',
        Cantine:'Cantine',
        Elèves:'Elèves',
        Admissions:'Admissions',
        Enseignement:'Enseignement',
        Absences:'Absences',
        Messagerie:'Messagerie',
        Paiements:'Paiements',
        Bulletin:'Bulletin',
        Timetable:'Emploi du temps',
        Curriculum:'Programme',
        Weeklyprograms:'Cahier journal',
        Assignment:'Exercice à faire',
        Correspondencebook:'Cahier de liaison',
        //fin

        //Enseignant
        Gestionbulletins:'Gestion des bulletins',
        Schoolcalendar:'Calendrier scolaire',
        ActivitycalendarIBSA:'Calendrier activités IBSA ',
        //fin

        //Parents
        Mychildren:' Mes enfants',
        WelcomeParents: 'Welcome to the Family-School Digital Link',
        ReregisterMychild:'Réinscrire mon enfant',
        Imsubscribingnow:"Je m'abonne maintenant ",
        Snacksandlunch:"Qu'est ce qu'on mange ?!",
        Lunchmenu:'Lunch menu',
        Designations:'DESIGNATIONS',
        Amountdu:'AMOUNT DUE',
        Amountpaid:'AMOUNT PAID',
        Balance:'BALANCE',

        //Fin



      },
    },
    ENGLISH: {
      langue: {
        siteInfo:"Develop a marketing strategy",
        siteTexte1:"We provide marketing content for your business,",

        MenuSite:"Site creation",
        MenuBussness:"Marketing",
        MenuAnnonce:"Become an advertiser",
        QuiSommeNous:"Who we are",

        Presentation:"We provide marketing content for your business",
        PresentationTexte1:"Bring your vision to life with our superior content creation services.",
        PresentationTexte2:"Grab the attention of your target audience with our creative and engaging content.",
        PresentationTexte3:"Maximize your online presence with our customized content creation strategy.",
        CreateMarketingContent:"Create marketing content",
        Createawebsite:"Create a website",

        TheListesecureManuel: 'Safety manual list',
        ThesecureManuel: 'Safety manual',
        Addthenewsletter: 'Add newsletters',
        ThePrincipalmailadresse: 'Email address of primary parent',
        ThePrincipalphonecontact: 'Main parent phone number',
        Thecantinefess: 'Canteen fees',
        AddingThecantinefess: 'Add canteen fees',
        MessagestandbyTovalidate: 'Messages waiting for validation',
        ThestatutValider: 'Validate',
        ThestatutStandby: 'Waiting for approval',
        ThestatutAlls: 'All',
        TheActions: 'Actions',
        TheMessageLibelle: 'Message wording',
        NoMessagestandbyTovalidate: 'No message waiting for validation',
        Theclasses: 'Class',
        ThedevoirLibelle: 'Assignment wording',
        TheAddby: 'Add by',
        TheFile: 'File',
        Thelien: 'Link',
        NoDevoirstandbyTovalidate: 'No pending assignments',
        DevoirstandbyTovalidate: 'Assignments awaiting validation',
        TheBtnClose: 'Close',
        PlanIsAccepted: 'Agreed plan',
        OurFamilies: 'Our family',
        Soldee: 'Paid',
        Solde: 'Sold',
        NoSoldee: 'Not sold',
        TheplanA: 'Plan A',
        TheplanB: 'Plan B',
        TheplanC: 'Plan C',
        TheplanD: 'Plan D',
        Atcharge: 'In charge of',
        MontantEcheance: 'Amount due',
        EcheanceDate: 'Due date',
        TheBtnDelete: 'Delete',
        AgreeFolder: 'Accept folder',
        AgreeCandidature: 'Accept application',
        Thedatails: 'Détails',
        SeePlan: 'See the plan',
        ChoiceTheclasse: 'Choice of class',
        Thestandby: 'On Standby',
        Thecurrently: 'In progress',
        TheValidateFolder: 'Folder validate',
        TheSbmitFolder: 'Folder submitted',
        TheStandbyFolder: 'Folder on hold',
        ThepaiementPlanSubmit: 'Payment plan submitted',
        TheStatutInscrit: 'Registered',
        Theperiodes: 'Periods',
        SelectTheperiodes: 'Select a period',
        TheFiles: 'Files',
        TheFilesStudents: "Student files",
        SubmitedBy: 'Submitted by',
        NoCahierstandbyTovalidate: 'No notebooks pending validation',
        CahierstandbyTovalidate: 'Notebooks pending validation',
        NoBulletinstandbyTovalidate: 'No reports card pending validation',
        BulletinstandbyTovalidate: 'Reports card pending validation',
        TheMatricules: 'Numbers',
        TheMatricule: 'Number',
        TransportManagement: 'Transport management',
        ThecircuitLists: 'List of routes',
        TheStandards: 'Standards',
        Themontantdu: 'Amount due',
        Themontantverser: 'Amount paid',
        TasksManagement: 'Task management',
        Reinscriptionform: 'Re-registration form',
        Inscriptionform: "Registration form",
        Candidatureform: "Application form",
        PreviousClasse: 'Previous class',
        Displayrecap: 'View summary',
        Absences:'Absences',
        Presences: 'Présences',
        Retards: 'Retards',
        ProfileUser: 'User profile',
        Nodocumentactually: 'No documents available',
        At:"To",
        Transportobservations:"Please fill in the amounts more than once separated by a dash (-)",
        AnnualFees3times:"Annual fee in 3 times",
        AnnualFees2times:"Annual fee in 2 times",
        AnnualFees1times:"Annual fee in 1 times",
        TrimestrialFees:"Trimester fee",
        MensualFees:"Monthly fee",
        TheMensual:"Mensual",
        ListTransportFees:"List of transportation costs",
        AddTransportFees:"Adding transportation costs",
        TheFees:"Fees",
        TheMontant:"Amount",
        TheTransportType:"Type of transport",
        TheSimpleTrajet:"Single route",
        TheMixteTrajet:"Mixed route",
        TheSimpleTrajetAllerRetour:"One way trip and return",
        TheSimpleTrajetAllerOuRetour:"One-way ticket to or from",
        TheCircuits:"Routes",
        TheRecapofDocument:"Document summary",
        TheSMSstatitics:"SMS AnalyticsS",
        TheUsed:"Use",
        TheUnUsed:"Residuals",
        TheTeacherAssistant:"Assistant teacher",
        TheTeacherAssistantList:"List of assistant teachers",
        TheRoles:"Roles",
        TheAVS:"AVS",
        TheAVSlist:"List of AVS",
        TheParents:"Parents",
        TheUsers:"Users",
        TheTimestablelists:"List of timetables",
        Recherchereffec:"Do a search",
        UpdateTimestablefile:"Modify the support of the timetable",
        ListOfStudents:"List of students",
        AllsStudents:"All students",
        Girlsudents:"Girls",
        Malesudents:"Boys",
        Girlsudent:"Girl",
        Malesudent:"Boy",
        TheInscrits:"Registered",
        TheReInscrits:"Re-registrants",
        TheTransfert:"Transfer",
        TheStandardList:"List of standards",
        ThesousStandardList:"list of sub standards",
        TheNewStandard:"New standard",
        TheNewsousStandard:"New sub standards",
        TheLangue:"Language",
        TheClassetypes:"Class types",
        ScolariesYearList:"List of academic years",
        ScolariesYear:"Academics years",
        AddScolariesYear:"Add a school year",
        TheEffectifs:"Memberships",
        TheActivestate:"Active",
        TheInActivestate:"Inactive",
        ListOfReportCards:"List of Report Cards",
        NoReportCardAvailaible: 'No report card available',
        BtnPublier:"Publish",
        TheObjet:"Object",
        NoListeAvailable:"No list available",
        TheLibelleFr:"Wording in Fr",
        TheLibelleEN:"Wording in En",
        AddThenewLibelle:"Add a new label",
        UpdateTheLibelle:"Mofify the wording",
        TheListofLibelle:"List of wordings",
        TheDaterainsList:"List of dates to remember",
        CandidaturesManagement:"Applications management",
        ThePrinted:"Print",
        ListofPrograms:"List of programs",
        Thenewprogram:"New program",
        TheVersementList:"List of payments",
        AddTheVersement:"Add payment",
        TheVersementDate:"Date payment",
        TheBeneficiaires:"Recipients",
        TheTrajets:"Routes",
        ThePrenameUsual:"Usual first name",
        TheNewassignation:"New assignment",
        AssignationAtEtabs:"Assignment to an establishment",
        TheProfile:"Profile",
        TheclasseNumbers:"Number of classes",
        AssignateAclasseForTeacger:"Assign a class to the teacher",
        ClasseAmount:"Amount of the class",
        Thetypes:"Types",
        ParentsList:"List of parents",
        ParentPrincipal:"Principal Parent",
        ParentSecondaire:"Secondary parent",
        FamilleLogin:"Family Login",
        ThecompteType:"Account type",
        Listedelaclasse:"List of the class",
        ExcelExport:"Export to excel",
        ExcelExportplus:"Export to excel with more details",
        TotalEffectif:"Total number",
        BtnConsulter:"Consult",
        BtnNoConsulter:"No Consult",
        ListeMenuCantine:"List of menus",
        StudentNumbers:"Number of students",
        ThedemandeList:"List of requests",
        ListeDescahierjournaux:"List of Notebooks",
        MontantAnnual:"Annual amount",
        MontantTrimestriel:"Trimester amount",
        ListeAccuserReceptions:"Acknowledgement list",
        Currentlyschools:"Current school",
        WhatisthefamilleStatus:"What is the status of this student's family?",
        SelectStatusofthisfaimily:"Select family status",
        Thenewsfaimily:"New family",
        Theoldersfaimily:"Older family",
        SearchTheloginfamille:"search for the family login",
        Theprofession:"Job title",
        TheEmployeur:"Employer",
        PostaleAdresse:"Postal address",
        TheEmetteurs:"Senders",
        TheSoumis:"Submitted",
        DateValidation:"Validation date",
        TheEtat:"Status",
        TheLastconnexion:"Last connection",
        TheconnectionNumbers:"Number of times connected",
        NeitherConnected:"Never connect",
        TodayConnected:"Connect today",
        TheclasseGallery:"Classroom Gallery",
        ManagementGallery:"Gallery Management",
        TheclasseListe:"Class list",
        CorrectifyBirthdays:"Correction of dates of birth",
        FolderValidation:"Validation of documents",
        ElevesSortants:"Outgoing students",
        Programsdetails:"Program details",
        Thegeneralinfos:"General information",
        MessageDetails:"Detail of the message",
        Messagerieboites:"Mail box",
        NewMessage:"New",
        Boitereceptions:"Inbox",
        Answered:"Answer",
        HmeworkDetails:"Details of the exercise to do",
        Classedetails:"Class Details",
        Candidaturestep1:" 1 A photo ID",
        Candidaturestep2:" 2 A birth certificate",
        Candidaturestep3:" 3 A vaccination certificate or a copy of the vaccination booklet",
        Candidaturestep4:" 4 The school booklet or the report card(s) from previous years",
        Candidaturestep5:" 5 Certificate of attendance or expulsion",
        FileImagetocandidate:"Type of file to add : Jpg,Jpeg,png",
        Filepdftocandidate:"Type of file to add : pdf",
        ChampObligatoires:"Required fields",
        PersonnalInformations:"Personal information",

        FileAttached:"Attached file",
        Nationalite2: 'Nationality 3',
        Listedateanniversaires:"List of anniversary dates",
        TheEtabs:"Establishments",
        TheMessageSends:"Sent messages",
        TheUnreadMessages:"Unread messages",
        TheAllMessages:"All messages",
        To:"From",
        ValiderAbulletin:"Validate a bulletin",
        ReceptionAccused:"Acknowledgement of receipt",
        AddAbulletin:"Add a report card",
        RdvParents:"Parents' meetings",
        ManagementCalendars:"Management of school calendars",
        IbsaCalendars:"IBSA Calendars",
        ParentaleAccord:"Parental consent",
        ClasseChangement:"Change of class",
        EtabsChangement:"Change of establishment",
        ClasseCurrent:"Current class",
        SelectDestinataires:"Select recipients",
        PaiementPlan:"Payment plan",
        ManageThedateRetains:"Management of dates to remember",
        WhatChildsTalents:"What would you say are your child's particular strengths and talents?",
        WhyIbsa:"Why did you choose IBSA?",
        WhatpsychoChild:"Has your child ever received a psycho/neuro-pedagogical evaluation? if yes, please provide copies of the report.",
        Isexpulseallready:"Has your child ever been suspended or expelled from school?",
        DoyoServiceconnexe:"Do you need the following school services?",
        InternatLogement:"Boarding school accommodation",
        Nobesoinsconnexe:"I don't need these services",
        Theother:"Other",
        RespoPrincipal:"Parents Main contact for the school team",
        WhoIsPrincipal:"Who is the main contact person?",
        WhoIsPrincipal:"Who is the main contact person?",
        TheFather:"Father",
        TheMother:"Mother",
        TheTutor:"Tutor",
        TheWhatsAppPhone:"WhatsApp contact",
        TheLocalisation:"Geographic address",
        TheCountry:"Country",
        TheTown:"City",
        TheQuatier:"District",
        TheSecondParent:"Second parent",
        TheNAchoice:"N/A (Check this box if there is no second parent to enter.)",
        WhoIsTheSecondParent:"Who is the second parent?",
        UrgencePerson:"Person to contact in case of emergency",
        HomePhone:"Residence",
        MedicalInfo:"Medical information",
        MedicalForm:"Medical Information Sheet",
        GroupeSanguin:"Blood group",
        TheClinique:"Clinic/Hospital",
        TheCliniqueMat:"Child / Clinic number",
        TheCMU:"CMU number",
        TheAssurance:"Policy number",
        TheMedicalAnte:"Medical background",
        TheEnfant:"Child",
        TheAsthme:"Asthma",
        TheDrepa:"Sickle cell disease",
        TheCardiopat:"Heart disease",
        TheEpilesp:"Epilepsy",
        TheHupert:"Hypertension",
        TheRhumat:"Rheumatism",
        TheSpiri:"Aspirin",
        TheMedcinTraitant:"Referring doctor",
        PhoneTheMedcinTraitant:"Telephone Attending doctor",
        TheAllergies:"Allergies",
        TheSerum:"Tetanus serum",
        TheNivaquine:"Nivaquine",
        ThePeniciline:"Penicillin",
        TheLode:"Lode",
        TheAllergieAliment:"Food allergy(ies)",
        TheOtherAllerg:"Other allergy",
        TheInfantdeases:"Childhood diseases",
        TheRougeol:"Measles",
        TheOreillonsl:"Mumps",
        TheVaricel:"Varicella",
        TheScartine:"Scarlet fever",
        TheNext:"Next",

        NbAbsences:"Number of absences",
        NbRetards:"Number of delays",
        Thestatitistics:"Statistics",
        TheWelcome:"Welcome",
        TheVersementState:"Status of payments",
        TheLoginBtn:"Login",
        Thescolarities:"Scolarities",
        Weeklydabalys:"Weekly menu",
        TheAtLe:"To",
        TheRef:"REF",
        PeriodeDu:"Period from",
        NoprogramAvailable:"No program available",
        Seeprogramme:"See the program",
        Whouldreinscrire:"I wish to re-enroll my child",
        Completefolder:"Complete the file",
        InfoAboutBulletin:"Report Card Information",
        Programsupport:"Program support",
        ProgramInfo:"Program information",
        TimestableInfo:"Information on the timetable",
        Messagefiltre:"Filtre messages",
        TheStudentInfos:"Student Information",
        TheclasseThat:"The class of",
        Myclasses:"My classes",
        Myclassinfo:"Class Info",
        NoHomeworkavailbale:"No exercises available",
        TheCahierjournaux:"Notebooks",
        UpdateProgramFiles:"Modify the program support",
        UpdateBulletinFiles:"Modify the report card holder",
        AddaTimestablenew:"Add a new timetable",
        Addanewnotebook:"Nouveau cahier journal",

        Thenewslettres:"Newsletters",
        Updatenewslettres:"Modify the newsletters",
        deletenewslettres:"Delete the newsletters",
        validatenewslettres:"Valider la newsletters",
        Nonewslettres:"No newsletters",
        dateparutionewslettres:"Date of publication",
        lienparutionewslettres:"Link to the newsletter",
        typeewslettres:"Newsletters type",
        lastnewslettres:"Latest newsletters",
        NoTimestables:"No timetable available",
        SelectNewsletterTypes:"Select a type",

        SearchingByprenom:"Search for a student by first name",
        FinancialDetails:"Financial information",
        TotalVersementInscrip:"Total Payments Registrations",
        TotalVersementReInscrip:"Total Payments Re-enrollments",
        TotalVersementScolarites:"Total Tuition Payments",
        TotalVersementTransports:"Total Transport Payments",
        TotalVersementAes:"Total AES payments",
        Thescolaritiescaps:"TUITIONS",
        Theinscriptioncaps:"REGISTRATIONS",
        Thereinscriptioncaps:"RE-REGISTRATIONS",
        Thetransportcaps:"TRANSPORTS",
        Theaescaps:"AES",
        Theversements:"Payments",






        BibliotheqeuNewsletters: 'Newsletters Library',
        BibliotheqeuCahiers: 'Notebook Library',
        Bibliothequemanagement: 'Library management',
        InscriptList: 'List of registrants',
        ReInscriptList: 'List of re-registrants',
        ActivitiesListe: 'List of activities',
        NewActivity: 'New activity',
        ManagementAES: 'Management of extra-curricular activities',
        FonctionAdmin: 'Administrateur',
        FonctionPolyvalent: 'Agent polyvalent',
        FonctionCE: "Chef d'établissement",
        FonctionChefcompta: "Chef comptable",
        FonctionBdm: "Business Development Manager",
        FonctionComptable: "Comptable",
        FonctionCoordinateur: "Coordinateur / Coordinatrice",
        FonctionCoordinateurCAes: "Coordinatrice des Admissions et AES ",
        FonctionCoordinateurCc: "Curriculum Coordinator",
        FonctionCoordinateurCd: "Curriculum Director",
        FonctionCoordinateurDaf: "Directeur / Directrice Administratif et Financier",
        FonctionCoordinateurDg: "Directrice générale",
        FonctionCoordinateurIntendance: "Intendance",
        FonctionCoordinateurMarketing: "Marketing",
        FonctionCoordinateurSuperviseur: "Superviseur",
        FonctionCoordinateurCharged: "Chargé des admissions",
        FonctionCoordinateurPcg: "Président du Conseil de Gestion",
        SelectTheFonction: 'Select a fonction',
        TheFonction: 'Fonction',
        TheFonctions: 'Fonctions',
        GenderF: 'F',
        GenderM: 'M',
        ThenewUser: 'New user',
        UsersLists: 'List of Users',
        ManagementParameters: 'Parameter management',
        UploadPhoto: 'Upload picture',
        Photo: 'Picture',
        ClassPhoto: 'Class Picture',
        StudentPhoto:"Student picture",
        SelectGenre: "Sélectionner un genre",
        ListofTeachers: "List of teachers",
        NewTeacher: "New teacher",
        SendMessage: "Send message",
        TheMessage: "Message",
        ObjetMessage: "Subject of the message",
        TitreMessage: "Title of the message",
        ManagementMessage: "Messaging management",
        TheSMS: "SMS",
        PrintedInvoice: "Print the invoice",
        SeeMore: "See more",
        Nopaiement: "No payment",
        Newpaiement: "New payment",
        Validatepaiement: "Validate the payment",
        Thedatepaiement: "Date of payment",
        Resteapeyer: "Remainder to pay",
        Montantversement: "Payment amount",
        Montantapayer: "Amount to pay",
        TheDu: "From",
        ModePaiementCheque: "Checks",
        ModePaiementEspece: "Cash",
        ModePaiementTpe: "TPE",
        ModePaiementVirement: "Bank transfer",
        SelectModePaiement: "Select payment method",
        ModePaiement: "Payment method",
        TrajetAllerRetour: "to and from",
        TrajetAllerouRetour: "to or from",
        SelectTheTrajet: "Select route",
        TheTrajet: "Route",
        TheAnnuel: "Annual",
        Thetrimestriel: "Trimestrial",
        SelectTheforfait: "Select package",
        Theforfait: "Package",
        SelectTheActivite: "Select activity",
        TheActivite: "Activity",
        TheAES: "AES",
        SelectTheMotif: "Select a reason",
        TheMotif: "Reason",
        TheMotifs: "Reasons",
        Thedeposantphone: "Depositor phone",
        Thedeposant: "Depositor",
        ManagementThepaiement: "Payment management",
        Thepaiement: "Payment",
        CantineManagement: "Canteen management",
        AddMenucantine: "Add a menu",
        TheLibelle: "Label",
        TheDatedeb: "Date of start",
        TheDatefin: "Date of end",
        TheTitre: "Title",
        Addpicture: "Add a picture",
        TheHomeworksupport: "Support for the assignment",
        TheNon: "NO",
        TheOui: "YES",
        Lockafterexpiration: "Lock the exercise on the student's side after the deadline",
        SelectStudent: "Sélect a student",
        BtnAnnuler: "Cancel",
        IndividualHomework: "Individual assignment",
        ClasseHomework: "Class assignment",
        TheLimitdate: "Deadline",
        LibelleHomeworks: "Wording of the assignment",
        NoTheMatiere: "No subject",
        SelectTheMatiere: "Select a subject",
        TheMatiere: "Subject",
        HomeworkInfo: "Information on the assignment",
        AddHomework: "Add new assignment",
        HomeworkLists: "List of assignments",
        TheDescription: "Description",
        FrDescription: "Description FR",
        AnDescription: "Description EN",
        TheHour: "Hour",
        TheAlls: "All",
        Destinataires: "Recipient(s)",
        SelectLibelleActiviteFr: "Select the label in FR",
        SelectLibelleActiviteEn: "Select the label in EN",
        LibelleActiviteFr: "Wording Activity (Fr)",
        LibelleActiviteEn: "Wording Activity  (En)",
        InfoAboutNationalHolidays: "Information on the national holiday",
        InfoAboutDatereatins: "Information on the date to remember",
        NationalHolidays: "National holidays",
        Addnewdate: "Add a new date",
        ListDateAndfetes: "List of dates and Calendar of National Holidays",
        CalendarNationalHolydays: "Calendar of National Holidays ",
        BtnSave: "Save",
        SelectNiveauClasse: "Select class level",
        NiveauClasse: "Class level",
        ReInscriptionsFees: "Re-registration fees",
        InscriptionsFees: "Registration fees",
        ScolaritesFees: "Tuition fees",
        LibelleclasseEn: "class label (English)",
        Libelleclassefr: "class label (French)",
        Newclasse: "New class",
        Listofclasses: "List of classes",
        ImportFile: "Import the file",
        SelectThestudent: "Select a student",
        Thestudent: "Student",
        SelectThetrimestre: "Select a trimester",
        Thetrimestre: "Trimester",
        OnReportcard: "on the report card",
        InfoTips: "Informations",
        AddnewreportCard: "Add a new report card",
        BtnValider: "Submit",
        StatutAbsent: "Absent",
        StatutRetard: "Late",
        StatutPresent: "Present",
        Thecommentaire: "Comment",
        SelectThestatut: "Select a Status",
        Thestatut: "Status",
        Thestatuts: "Status",
        NameAndPrename: "First & last names",
        SelectTheclasse: "Select a class",
        Theclasse: "Class",
        Admin: "Administration",
        Teacher: "Teacher",
        SelectTeacher: "Select a teacher",
        Teachers: "Teachers",
        SelectThePersonneltype: "Select the type of staff",
        ThePersonnel: "Staff",
        Thedate: "Date",
        StudentAttendences: "Student attendance",
        StaffAttendences: "Staff attendance",
        RecapStudentAttendences: "Student attendance report",
        RecapStaffAttendences: "Staff attendance report",
        ManagementAbsences: "Attendance management",
        TheAbsences: "Attendance",
        Reregistrationdemande: 'Re-registration request',
        hello: 'Welcome to the Family-School Digital Link',
        Home: 'Home',
        Calendriers: 'Calendars',
        Candidatures: 'Candidacies',
        Enquetes: 'Survey',
        GestionsEleves: 'Student management',
        Eleves: 'Students',
        Transports: 'Transportations',
        Enseignement: 'Education',
        Enseignements: 'Educations',
        Assiduites: 'Attendance',
        Bulletins: 'Bulletins',
        Bibliotheque: 'Library',
        AExtra: 'Extracurricular Activities',
        Messages: 'Messages',
        Administration: 'Administration',
        Galerie: 'Gallery',
        Tasks: 'Tasks',
        Dateretains: 'Date to remember',
        Francais: 'French',
        Anglais: 'Anglais',
        Inscription: 'Registration',
        Inscriptions: 'Registrations',
        Reinscription: 'Re-registration',
        Reinscriptions: 'Re-registrations',
        Familles: 'Families',
        FamillesListes: 'List of families',
        Classes: 'Classes',
        Monitoring: 'Monitoring',
        HitoriqueCnx: 'Connection statistics',
        HistoriqNotifs: 'Notifications history',
        HistoriqCahiers: 'History of the notebooks',
        Deconnexion: 'Logout',
        Account: 'My account',
        CahierJournal: 'Weekly programs',
        Cahierliaison: 'Communication diary',
        Devoirs: 'Homeworks',
        Cantines: 'Cantines',
        Anneescolaires: 'Academic year',
        Emploisdutemps: 'Timetable',
        Programmes: 'Curriculum',
        Programme: 'Curriculum',
        Calendrierscolaire: 'Academic calendar',
        ManuelParent: 'Parent handbook',
        Accountdetails: 'Account details',
        Changepictureprofile: 'Change the profile picture',
        Choosepicture: 'Choose an image',
        Informations: 'Informations',
        Accountinfos: 'Account info',
        Parameters: 'Settings',
        FavoriteLangue: 'Preferred language',
        AccountName: 'Account name',
        Name: 'Last Name',
        PreName: 'First names',
        Genre: 'Kind',
        Masculin: 'Male',
        Feminin: 'Female',
        Datenais: 'Date of birth',
        Lieunais: 'Place of birth',
        Nationalite: 'Nationality',
        Nationalite1: 'Nationality 2',
        Fonction: 'Function',
        AdresseEmail: 'Email address',
        Telephone: 'Cell phone',
        MobileTelephone: 'Mobile phone',
        WorkTelephone: 'Office phone',
        Leschamps: 'The fields ',
        Obligatoires: 'are required ',
        ModifierBtn: 'Edit',
        ParametresCnx: 'Connection settings',
        Login: 'Login',
        Password: 'Password',
        Password1: 'Confirm password',
        PleaseAddpasswords: 'Please fill in the passwords',
        PleaseAddthesamepasswords: 'Please enter the same passwords',
        PleaseAddChampsObligatoires: 'Please fill in the required fields',
        Emploisdutemps: 'Timetable',
        Programmes: 'Curriculua',
        Calendrierscolaire: 'Academic calendar',
        Parentskit:'Parents kit',
        ManuelParent: 'PARENTS HANDBOOK',
        SchoolCalendar:'SCHOOL CALENDAR',
        Curriculum:'CURRICULUM',
        Weeklyagenda:'Weekly agenda',
        Digitalteachingtools:'Digital teaching tools',
        FriendsofIBSA:'Friends of IBSA',
        IBSAHighSchoolDiploma:'IBSA High School Diploma',
        Datestoremember:'Dates to remember',
        PaymentsHistory:'Payments History',
        PaymentsHistoryAES:'AES Payments History',
        Myschoolapps:'My school apps',
        Studentsheet:'Student sheet',
        Weeklyprograms:'Weekly programs',
        Correspondencebook:'Correspondence book',
        Reportcards:'Report cards',
        Absences:'Absences',
        tardiveness:'tardiveness',
        Parentconferences:'Parent/teacher conferences',
        Document:'Document',
        Gallery:'Gallery',
        Weekof:'WEEK OF',
        Assignement:'Assignement',
        Downloader:'To download',
        //Menu
        Souscriptions:'Services',
        Cantine:'Cafetaria',
        Elèves:'My Kids',
        TheEleves: 'Students',
        Admissions:'Admissions',
        Enseignement:'Education',

        Messagerie:'messages',
        Paiements:'Payments',
        Bulletin:'Report cards',
        Timetable:'Timetable',
        Curriculum:'Curriculum',
        Weeklyprograms:'Weekly programs',
        Assignment:'Assignment',
        Correspondencebook:'Correspondence book',

         //Enseignant
        Gestionbulletins:'Bulletin management',
        Schoolcalendar:'School calendar',
        ActivitycalendarIBSA:'Activity calendarIBSA',
       //fin


        //Parents

        Mychildren:'My children',
        WelcomeParents: 'Welcome to the Family-School Digital Link',
        ReregisterMychild:'Re-register my child',
        Imsubscribingnow:"I'm subscribing now",
        Snacksandlunch:'Snacks and lunch',
        Lunchmenu:'Lunch menu',
        Designations:'DESIGNATIONS',
        Amountdu:'AMOUNT DUE',
        Amountpaid:'AMOUNT PAID',
        Balance:'BALANCE',
        //Fin



      },
    }
  };

  export default Langues;
